### ISSUE TITLE
Quickstart is not working when invoked via openshift "create application" web interface

### ISSUE THREAD

**Issue by abonas** [openshift-quickstart/openshift-ghost-quickstart#19]
When trying to use the quickstart via openshift's web interface (under applications - create an application)
example link: https://openshift.redhat.com/app/console/application_type/quickstart!16263
It outputs "Application creation is taking longer than expected. Please wait a few minutes, then refresh this page.", and then nothing is created.
In some cases it leads to 
" We appear to be having technical difficulties.Unhandled exception reference #a847a7bdec1a97a17078a655970b5969: The thread #<Thread:0x007f78100d9a28 aborting> (index=1) did not complete within 10 seconds"
And again, nothing is created.
Via command line with rhc it works fine.

**Comment by corey112358** [comment]
quickstart has been upgraded

**Comment by camilodelvasto** [comment]
@Gexos thanks for the quick tutorial. I was doing the same you described but found a problem I don't know how to deal with: I installed ghost locally (not from the quickstart) and created a theme, which works fine on my local install. I tried cloning this theme (which for the moment is just a copy of casper with a different name and version) in the /content/themes folder from the repo open shift gave me. After pushing, I can see in my openshift ghost blog that the new theme is there, but the theme is broken.... so it displays only the name, not the version. and of course if I select it, it displays a 500 error:

Failed to lookup view "index" in views directory "/var/lib/openshift/559eec785004461bd30000e2/app-root/runtime/repo/content/themes/starticsghost"
https://www.dropbox.com/s/rsaonscvxr8i9yt/Screenshot%202015-07-09%2017.28.24.png?dl=0
Would you know where the problem is? Thanks!
