### ISSUE TITLE
After upgrade app says theme is missing

### ISSUE THREAD

**Issue by cleversprocket** [openshift-quickstart/openshift-ghost-quickstart#47]
I upgraded from 0.5.7 to 0.6.4 using this repo and when I go to the site (www.wavokicrafts.com) it says the custom theme is missing. 

Following the upgrade steps in the readme did not work, (`npm update`). So I followed the upgrade steps on ghost's support page by deleting the old code base but keeping `/content` and `config.js` and copying over this repo. The one thing I didn't copy over is `node_modules`. I noticed `node_modules` has a `ghost` module which contains the build, which is unfamiliar to me. Is the app looking for the theme in `./node_modules/ghost/content/themes`? If so is this where I should be adding my custom theme?

![image](https://cloud.githubusercontent.com/assets/3432985/8323799/0036d91e-19fe-11e5-9286-b7610b509b1e.png)

**Comment by MunGell** [comment]
Hi @cleversprocket 

Have you used this repo for the initial install of 0.5.7?

Since 0.5.6 we have changed the file structure and moved Ghost into `node_modules`, so it is now possible to update to the latest version of Ghost by simply running `npm update` and avoid deleting/adding all Ghost files manually.

Your custom themes should be placed in [content/themes](https://github.com/openshift-quickstart/openshift-ghost-quickstart/tree/master/content/themes) directory in root of this repository.

**Comment by cleversprocket** [comment]
HI @MunGell no I've been using this repo since before 0.5.6  

Ok, I see this app depends on `ghost` which is a good move. My custom theme is placed in `content/themes`. I see that `./config.js` has changed and I didn't copy that over. I think [paths](https://github.com/openshift-quickstart/openshift-ghost-quickstart/blob/master/config.js#L127) is the reason my app isn't finding the theme. I'm pushing the change and will comment if that fixed it.

**Comment by cleversprocket** [comment]
Yup, that fixed it.
